### ISSUE TITLE
Unsupported features

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#14]
Background issue at https://github.com/sindresorhus/execa/issues/1147

nano-spawn's design goal is to have a small package size. As such, it is intentionally missing some features. [Execa](https://github.com/sindresorhus/execa/) provides with those missing features, if a user needs them. Alternatively, users have access to the underlying `subprocess`, so they can achieve most of what they want.

This issue lists those missing features:
- [Synchronous execution](https://github.com/sindresorhus/execa/blob/main/docs/execution.md#synchronous-execution)
- [Binary input/output](https://github.com/sindresorhus/execa/blob/main/docs/binary.md)
- [Multiple input/output](https://github.com/sindresorhus/execa/blob/main/docs/output.md#multiple-targets)
- [File input/output](https://github.com/sindresorhus/execa/blob/main/docs/output.md#file-output) (see #19)
- Node.js or web streams (as opposed to iterables). However, users will be able to pass those to the native `stdin`/`stdout`/`stderr` option, e.g. `{stdout: createWriteStream('./output.txt')}`.
- [Graceful termination](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#graceful-termination)
- [Custom logging](https://github.com/sindresorhus/execa/blob/main/docs/debugging.md#custom-logging)
- [IPC](https://github.com/sindresorhus/execa/blob/main/docs/ipc.md)
- [REPL-like input string](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#user-defined-input)
- Additional file descriptors can be set through the underlying native option `stdio`. However, they cannot be [iterated](https://github.com/sindresorhus/execa/blob/main/docs/api.md#readableoptionsfrom) nor [retrieved](https://github.com/sindresorhus/execa/blob/main/docs/output.md#additional-file-descriptors).
- Setting a [max size](https://github.com/sindresorhus/execa/blob/main/docs/output.md#big-output) for the output.
- Preventing the [subprocess to throw](https://github.com/sindresorhus/execa/blob/main/docs/errors.md#preventing-exceptions). Due to this there is also no need for a `result.failed`/`error.failed` boolean.
- [Terminate the subprocess](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#current-process-exit) when the current process exits.
- [Forceful termination](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#forceful-termination) after a delay
- [Script interface](https://github.com/sindresorhus/execa/blob/main/docs/scripts.md)
- [Template string syntax](https://github.com/sindresorhus/execa/blob/main/docs/execution.md#template-string-syntax)
- Keeping the [final newline](https://github.com/sindresorhus/execa/blob/main/docs/lines.md#final-newline)
- Splitting the [output in lines](https://github.com/sindresorhus/execa/blob/main/docs/lines.md#array-of-lines) (the final output, not when iterating)
- [Global/shared options](https://github.com/sindresorhus/execa/blob/main/docs/execution.md#globalshared-options)
- [Provide a stack trace](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#error-message-and-stack-trace) when terminating the subprocess
- Shebangs on [Windows](https://github.com/sindresorhus/execa/blob/main/docs/windows.md) (see #12)
- Custom Node.js binary (e.g. without ICU)
- [Transforms](https://github.com/sindresorhus/execa/blob/main/docs/transform.md)
- [Current directory](https://github.com/sindresorhus/execa/blob/main/docs/environment.md#current-directory) in the result
- Booleans on the error object indicating the [subprocess failure reason](https://github.com/sindresorhus/execa/blob/main/docs/errors.md#failure-reason): timeout, cancelation, signal termination, etc. 
- [Verbose mode](https://github.com/sindresorhus/execa/blob/main/docs/debugging.md#verbose-mode)
- Advanced piping:
  - Piping [from `stderr`](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#source-file-descriptor), both `stderr`+`stdout`, or other file descriptors
  - Piping to [other file descriptors than `stdin`](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#destination-file-descriptor)
  - Piping multiple subprocesses [to one](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#multiple-sources-1-destination)
  - [Cancelling piping](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#unpipe)

@sindresorhus Please let me know if this list is incorrect.

**Comment by felipecrs** [comment]
Any library suggestions for converting a command line string into command + args for executing with nano-spawn?

I'm trying to move away from execa through nano-spawn, but I cannot skip this part.

[args-tokenizer also has issues with Windows](https://github.com/TrySound/args-tokenizer/issues/2).

**Comment by ehmicky** [comment]
The problem with parsing a string of command arguments into a JavaScript array of arguments is escaping/quoting. 

You need to pick one specific pattern for escaping/quoting. For example, Unix shells uses one way, `cmd.exe` uses another. With Execa, we use yet another that's simpler (no quoting, spaces are delimiters unless backslash escaped). 

My experience is: regardless of which you pick, your users will be confused. That's because there's no universal way to escape/quote. Also, users often spawn processes that spawn other processes, which mean double or triple escaping might be involved. If you had the fact that escaping/quoting is critical to avoid command injection, this makes this a complex problem.

Another issue is users do not always quite distinguish between the following separate concepts:
  - At the OS level, Unix just executes an array of arguments. It does not need escaping or quoting, since this happens in C where you just supply an array where each argument is already separated from each other. Side note: Windows works the opposite way there, where the OS syscall actually uses a concatenated string of arguments, that's assumed to use `cmd.exe`-style escaping.
  - Then, the command might (or not) be run inside a shell. Since shells are often run in interactive terminals, where user input is entered as a string, they have developed their unique shell-specific escaping/quoting syntax.

So, for example, `args-tokenizer` seems to be mimicking a simplified version of Unix shell quoting rules. So it probably intentionally handles backslashes the Unix way, which means does not work well with Windows file separators.

In general, due to all of the above, my advice would be, as a library author, to try to provide APIs where users pass arrays of arguments instead of a concatenated string. Although at first it seems more complicated for your users, it actually ends up being much clearer and can solve quite many headaches, GitHub issues and potential security concerns.

If you have a use case where a string is absolutely needed, for example a CLI, then you need to pick one escaping/quoting rule. `args-tokenizer` seems fine, and there you'll choose Unix-style escaping. If you're interested in the one we use in Execa, the [code is here](https://github.com/sindresorhus/execa/blob/a31fe55782993f2483d30955a8799ab88e20687c/lib/methods/command.js#L18).

**Comment by felipecrs** [comment]
@ehmicky absolutely understood. Thanks a lot for the great explanation.

I completely agree I should try as hard as possible to avoid using a parser at all (prefer user-supplied arguments list instead).

But I'm not ready to make this move just yet, and I am completely fine with adopting a certain pattern/style.

In my case, the pattern is execa's.

> If you're interested in the one we use in Execa, the [code is here](https://github.com/sindresorhus/execa/blob/a31fe55782993f2483d30955a8799ab88e20687c/lib/methods/command.js#L18).

Thanks for providing the reference!

And I believe this piece of code could become a tiny library by following @sindresorhus's opinion:

https://sindresorhus.com/blog/small-focused-modules

What do you think?

**Comment by ehmicky** [comment]
I think the underlying problem here is a conflict (that many users might find, including myself) between wanting both:
  - `nano-spawn` for its smaller size
  - Execa, but only for some specific features

At the moment, for simplicity, we made it a binary choice: you either opt for missing some features, or for a bigger dependency. So we might get similar requests, for example: split the logic related to output line splitting from Execa, shebangs on Windows, etc.

Using small modules is one way to solve this. However, in this specific case, the feature at stake is a pattern that we want to generally discourage for the reasons mentioned above. It is kept in Execa mostly for backward compatibility and edge cases. Based on this, I would personally not split it from Execa into a small module. 

However, you can re-use the code from Execa and/or publish it as a small module. 👍

**Comment by felipecrs** [comment]
Fair enough. Thank you.

PS: I have no plans to publish it myself as the code is not mine.
