### ISSUE TITLE
Break down `stdio` option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#15]
Breaking down the `stdio` option into 3 options (`stdin`/`stdout`/`stderr`) is quite a nice thing. Also, it should be fairly short to implement.

```js
const exampleFunction = ({stdin, stdout, stderr, stdio = [stdin, stdout, stderr], ...options}) => {
  spawn(..., {...options, stdio});
}
```

We could also limit the documentation of those options:
- Only document: `'pipe'`, `'ignore'`, `'inherit'`
- Do not fully document`'overlapped'`, `'ipc'`, Node.js stream, file descriptor integer, `null`/`undefined` (as an alias for `'pipe'`), file descriptors beyond 0/1/2. Only include a link to the Node.js documentation, saying that those values are also available (but not fully documented).

What do you think?

**Comment by sindresorhus** [comment]
Yes, this is a nice shortcut.
