### ISSUE TITLE
String input

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#16]
Providing a string to `stdin` is quite useful.  It prevents users from manipulating Node.js streams. It's also quite small to implement. What do you think about providing this feature?

If so, what are your thoughts on re-using the `stdin` option (see #15)?  This would keep the API small, by avoiding creating a separate option.  It's also clearer since it directly impacts `stdin`.  Most importantly, it would prevent specifying a string as input while still setting `stdin` to something like `'inherit'`. By re-using the same option, we don't need to add any logic to prevent this case, which would keep our code small.

Possible syntax (anything else that's not ambiguous works): `{stdin: {raw: 'string'}}`

```js
if (options.stdin?.raw) {
  subprocess.stdin.end(options.stdin.raw);
}
```

What do you think?

**Comment by sindresorhus** [comment]
I like the consistency of having:

```js
{stdin: 'pipe'}
{stdin: {raw: 'string'}}
{stdin: {filePath: '/foo'}}
```

But I wish the most common case of passing in a string was less verbose...

Maybe we could still have a `input` option that just accepted a string as a convenience?

**Comment by ehmicky** [comment]
Which would you prefer? Either works for me. :+1:

**Comment by sindresorhus** [comment]
Some more alternatives:

#### 1

```js
{stdin: 'pipe'}
{stdin: nanoSpawn.input('dasds')}
{stdin: nanoSpawn.fileInput('/foo')}
```

#### 2

```js
{stdin: nanoSpawn.flag('pipe')}
{stdin: 'dasds'}
{stdin: new URL('/foo')}
```

#### 3

```js
{stdin: {type: 'pipe'}}
{stdin: 'dasds'}
{stdin: new URL('/foo')}
```

**Comment by sindresorhus** [comment]
Maybe we just do `{stdin: {string: 'string'}}` for now? Should be easy to adapt it to whatever we decide later on.

**Comment by ehmicky** [comment]
Sounds good.

I started implementing it and realized that it would take the same amount of bytes to support `string | Uint8Array` instead of only `string`. That's because we'd be using `subprocess.stdin.end(value)`, which supports both types.

Should we also support `Uint8Array` then?

**Comment by sindresorhus** [comment]
I prefer being consistent and only supporting `string`. Would also be weird to do `{stdin: {string: someUint8Array}}`.
