### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#64]
We have 100% test coverage (except for two lines which can intentionally never be reached).

What are your thoughts on adding Codecov, so we can put a "100% tested" badge on the readme?

**Comment by sindresorhus** [comment]
Codecov fails all the time and is just annoying. Maybe we just add c8 locally and then add a static badge:

```
https://img.shields.io/badge/coverage-100%25-green
```

**Comment by ehmicky** [comment]
This works. :+1:
