### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#77]
After adding the documentation (#76), I'll create a PR to add this documentation to the types.

Once this is done, I think we're ready for a release! :tada: 

Maybe it should be `0.1.0` for a little bit since this is quite new?

**Comment by sindresorhus** [comment]
> Maybe it should be 0.1.0 for a little bit since this is quite new?

Yeah. Let's try it out in practice before committing to the API.

**Comment by sindresorhus** [comment]
Feel free to do the honors, since you have done all the work. We don't really need any release notes as no one is using this yet.

**Comment by ehmicky** [comment]
Released!

https://github.com/sindresorhus/nano-spawn/releases/tag/v0.1.0
