### ISSUE TITLE
Reject the promise on non-0 exit code

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/nano-spawn#8]
If either `result.exitCode` is non-0 or `result.signalName` is `undefined`, the promise should be rejected.

We should also make sure `result.exitCode` and `result.signalName` are never `null` (as opposed to `undefined`).

**Comment by felipecrs** [comment]
> From the https://github.com/sindresorhus/execa/issues/1147#issuecomment-2297080114 from @sindresorhus, we decided to leave it out in nano-spawn, to keep the code size small:

I can't imagine that such logic would make a relevant increase in the code size. But I understand, the decision is yours.

> However, you should be able to easily wrap `nano-spawn` with a `catch` block to customize behavior? This also gives you some freedom in what case you want an error to be thrown or not:
> * non-0 exit code: `error.exitCode !== undefined`
> * signal termination: `error.signalName !== undefined`
> * anything else: most likely, stream errors or options validation error

Indeed, in my case I'd only want to suppress the non-0 exit code rejection - not the other ones. Which makes me wonder if `execa` shouldn't allow for more granular controls, like `rejectOnExitCode: false`, `rejectOnSignal: false`, etc.
